### ISSUE TITLE
TypeError when upgrading to 1.3.9

### ISSUE THREAD

**Issue by dagstuan** [apexcharts/react-apexcharts#311]
Hello, when I attempt to compile my app with TypeScript with `react-apexcharts@1.3.9` I get the following error:

```
node_modules/react-apexcharts/types/react-apexcharts.d.ts:30:47 - error TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.

30   export default class ReactApexChart extends React.Component<Props> {}
```

I have to downgrade to `1.3.7` to avoid the error.

**Comment by ifonetwork** [comment]
Adding import React from 'react'; to  react-apexcharts.d.ts will solve the issue

**Comment by ifonetwork** [comment]
Same issue. Adding import React from 'react'; to react-apexcharts.d.ts will solve the issue

**Comment by dagstuan** [comment]
Any news on this? I still can't upgrade...

**Comment by AyushBhadauria** [comment]
I am facing the same issue on` 1.3.7` as well

**Comment by junedchhipa** [comment]
Released v1.4.0 which fixes this issue.
